"""The portfolio check-up: deterministic observations about how your money is spread.

Still the analysis layer, so still plain Python with no LLM anywhere near it. This is hard
rule #1 applied to the risk numbers: ``risk.py`` already works out concentration, the biggest
holding's weight, the effective number of holdings and the sector split, and until now none of
it reached the screen. Each check here turns one of those figures into a sentence, **composed
in code**, the same way ``market/client.py`` composes a company blurb from the provider's own
fields rather than asking a model to write one.

Hard rule #2 shapes every word. A check **observes and explains**, it never prescribes:

- It says "AAPL is 62% of what you own", never "you should trim AAPL".
- It is named for the fact it measures, not for a verdict on the user ("How much rides on one
  company", not "Dangerous concentration"), the same naming rule the badges follow.
- The two states are ``ok`` and ``notable``, not "good" and "bad". Something being notable
  means it's worth understanding, not that it's a mistake. Plenty of people deliberately hold
  one stock or a pile of cash, and the lesson text says so.

A check that cannot apply is left out entirely rather than shown as empty, which keeps the
list short for someone who owns two things. ``unknown`` exists only for a check we *should*
be able to run but had no data for, which today means the sector split when a profile lookup
failed.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from typing import Literal

_ZERO = Decimal(0)
_ONE = Decimal(1)

Status = Literal["ok", "notable", "unknown"]

# One position this far past a share of the holdings means the portfolio's fate mostly rides
# on one company. 40% is a judgement call, not a law; it is roughly where "I own some of that"
# turns into "I own that".
BIG_POSITION_PERCENT = Decimal(40)

# Fewer than this many companies is few enough that one bad day shows up in the total.
FEW_COMPANIES = 3

# The Herfindahl "effective number of holdings": how many equally sized bets the portfolio
# actually behaves like. Below two means that however many names are on the list, it moves
# like one or two of them. Only interesting once there are at least three names, otherwise it
# is just restating the biggest-position check.
THIN_SPREAD = Decimal(2)
SPREAD_MIN_POSITIONS = 3

# One industry past this share of the holdings means the names are different but the bet
# mostly is not. Needs at least two positions to be worth saying.
CROWDED_SECTOR_PERCENT = Decimal(60)
SECTOR_MIN_POSITIONS = 2

# Cash past this share of the whole portfolio is a large deliberate position in doing nothing.
LOTS_OF_CASH_PERCENT = Decimal(50)


@dataclass(frozen=True)
class PortfolioFacts:
    """Everything the checks look at, and nothing else.

    All the weights are percents. ``top_weight`` and ``top_sector_weight`` are shares of the
    holdings alone; ``cash_weight`` is a share of the whole portfolio, cash included, which is
    the same split ``risk.concentration`` uses. ``top_sector`` is ``None`` when no sector could
    be labelled, which is the difference between "spread across industries" and "we don't know".
    """

    position_count: int
    top_symbol: str | None
    top_weight: Decimal
    effective_holdings: Decimal
    cash_weight: Decimal
    top_sector: str | None
    top_sector_weight: Decimal


@dataclass(frozen=True)
class Finding:
    """One check's reading of this account.

    ``detail`` is the sentence with the figure in it, composed here in code from a number the
    analysis layer worked out. ``lesson`` is the static teaching copy behind it, written by a
    person. Neither is ever generated by a model.
    """

    key: str
    title: str
    status: Status
    detail: str
    lesson: str


def evaluate(facts: PortfolioFacts) -> list[Finding]:
    """Every check that applies to this account, in display order.

    Pure and total: the same facts always give the same findings, and it never reads a clock,
    a database or a price. An account holding nothing gets an empty list, since there is
    nothing yet to say anything honest about.
    """
    if facts.position_count <= 0:
        return []

    findings = [
        _one_big_position(facts),
        _how_many_companies(facts),
        _spread_of_bets(facts),
        _sector_spread(facts),
        _cash_on_the_sidelines(facts),
    ]
    return [finding for finding in findings if finding is not None]


def _one_big_position(facts: PortfolioFacts) -> Finding | None:
    if facts.top_symbol is None:
        return None
    big = facts.top_weight >= BIG_POSITION_PERCENT
    share = _percent(facts.top_weight)
    return Finding(
        key="one_big_position",
        title="How much rides on one company",
        status="notable" if big else "ok",
        detail=(
            f"{facts.top_symbol} is {share} of what you own, so how you do mostly comes down "
            f"to that one company."
            if big
            else f"Your biggest position, {facts.top_symbol}, is {share} of what you own."
        ),
        lesson=(
            "When one company is most of what you hold, your results are basically that "
            "company's results. That cuts both ways: it's how people make a lot quickly, and "
            "it's how they lose a lot quickly. Neither is wrong on purpose, it just means the "
            "swings you feel are about one business rather than the market."
        ),
    )


def _how_many_companies(facts: PortfolioFacts) -> Finding:
    few = facts.position_count < FEW_COMPANIES
    companies = "company" if facts.position_count == 1 else "companies"
    return Finding(
        key="how_many_companies",
        title="How many companies you own",
        status="notable" if few else "ok",
        detail=f"You own {facts.position_count} {companies}.",
        lesson=(
            "Owning more companies means one of them having a terrible week matters less. "
            "That's diversification, and it's about the closest thing to a free lunch in "
            "investing: the wild swings smooth out without costing you much over the long "
            "run. It doesn't protect you when the whole market falls, though. Nothing does."
        ),
    )


def _spread_of_bets(facts: PortfolioFacts) -> Finding | None:
    # With one or two names this only repeats the biggest-position check, so skip it.
    if facts.position_count < SPREAD_MIN_POSITIONS or facts.effective_holdings <= _ZERO:
        return None
    thin = facts.effective_holdings < THIN_SPREAD
    behaves_like = _round(facts.effective_holdings, Decimal("0.1"))
    return Finding(
        key="spread_of_bets",
        title="How evenly it's split",
        status="notable" if thin else "ok",
        detail=(
            f"You hold {facts.position_count} companies, but the split means it moves like "
            f"about {behaves_like} equally sized bets."
        ),
        lesson=(
            "Counting names overstates how spread out you are when one of them is most of the "
            "money. This number asks a fairer question: if all your positions were the same "
            "size, how many would it take to move the way yours actually moves? A list of ten "
            "that behaves like one and a half is really a bet on one and a half things."
        ),
    )


def _sector_spread(facts: PortfolioFacts) -> Finding | None:
    if facts.position_count < SECTOR_MIN_POSITIONS:
        return None
    if facts.top_sector is None:
        return Finding(
            key="sector_spread",
            title="Whether you're spread across industries",
            status="unknown",
            detail="We couldn't look up what industries your companies are in just now.",
            lesson=_SECTOR_LESSON,
        )
    crowded = facts.top_sector_weight >= CROWDED_SECTOR_PERCENT
    share = _percent(facts.top_sector_weight)
    return Finding(
        key="sector_spread",
        title="Whether you're spread across industries",
        status="notable" if crowded else "ok",
        detail=(
            f"{share} of what you own is in one industry, {facts.top_sector}."
            if crowded
            else f"Your biggest industry is {facts.top_sector}, at {share} of what you own."
        ),
        lesson=_SECTOR_LESSON,
    )


_SECTOR_LESSON = (
    "Five different companies in the same industry aren't really five different bets. When "
    "something hits that industry, they tend to fall together, so the protection you thought "
    "you had from owning several isn't there. Spreading across industries is what makes owning "
    "several actually count for something."
)


def _cash_on_the_sidelines(facts: PortfolioFacts) -> Finding:
    lots = facts.cash_weight >= LOTS_OF_CASH_PERCENT
    share = _percent(facts.cash_weight)
    return Finding(
        key="cash_on_the_sidelines",
        title="How much is still cash",
        status="notable" if lots else "ok",
        detail=(
            f"{share} of your money is still sitting in cash."
            if lots
            else f"You've got {share} of your money in cash."
        ),
        lesson=(
            "Cash is a position too, and it's the one that doesn't move. It can't drop when "
            "the market drops, and it can't grow when the market grows. Holding a pile of it "
            "on purpose is a real choice plenty of people make, and holding it because you "
            "haven't decided yet is a different thing that looks identical on the screen. "
            "Worth knowing which one you're doing."
        ),
    )


def _percent(value: Decimal) -> str:
    """A weight as a whole-number percent. Sentences read better without the decimals."""
    return f"{_round(value, _ONE)}%"


def _round(value: Decimal, places: Decimal) -> Decimal:
    return value.quantize(places, rounding=ROUND_HALF_UP)
